### Gradle properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

### Mod Gradle properties
net.minecraftforge.gradle.merge-source-sets=true
fabric.loom.disableObfuscation=true
multiloader.enableAdvancedVersionSearch=true
multiloader.editPublishVersions=true

### Mod properties
mod.name=Campfire Dries Ghasts
mod.id=dry_ghast
mod.version=1.0
mod.description=Turns happy ghasts back into dried ghasts with campfire smoke

### Publishing
mod.modrinth=JCaVIxVy
mod.curseforge=1712626
mod.github=campfire-dries-ghasts
